version: '3'

services:
  pw-backend:
    image: ghcr.io/GeneralMagicio/pw-backend:staging
    container_name: rpgf4-pw-backend
    restart: always
    ports:
      - 7071:7070
    networks:
      - pw-backend
    volumes:
      - ./data:/usr/src/app/data

networks:
  pw-backend:
