// Type definitions for badge data
export type RawSnapshotPoint = {
  User: string;
  holderPoints: string;
  delegatePoints: string;
  holderAmount: string;
  delegateAmount: string;
  recipientsPoints: '0' | '1';
  badgeholderPoints: '0' | '1';
  holderType:
    | 'Bronze'
    | 'Diamond'
    | 'Platnium'
    | 'Gold'
    | 'Silver'
    | 'WHALE'
    | 'null';
  delegateType:
    | 'Bronze'
    | 'Diamond'
    | 'Platnium'
    | 'Gold'
    | 'Silver'
    | 'WHALE'
    | 'null';
};

export const snapshotPoints: RawSnapshotPoint[] = [
  {
    User: 'olimpio.eth',
    holderPoints: '50',
    delegatePoints: '1',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'Bronze',
    holderAmount: '7856737',
    delegateAmount: '2063',
  },
  {
    User: 'GFX Labs',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '4905',
  },
  {
    User: '0x1689...D374',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '4044',
  },
  {
    User: 'Lefteris Karapetsas …',
    holderPoints: '0',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x406b...c159',
    holderPoints: '0',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'moenick.eth',
    holderPoints: '25',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '35393',
    delegateAmount: '0',
  },
  {
    User: 'jackanorak.eth',
    holderPoints: '50',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '5960969',
    delegateAmount: '0',
  },
  {
    User: 'notscottmoore',
    holderPoints: '25',
    delegatePoints: '10',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '40141',
    delegateAmount: '0',
  },
  {
    User: 'Michael Vander Meide…',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '944256',
    delegateAmount: '0',
  },
  {
    User: 'she256.eth',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'Penn Blockchain',
    holderPoints: '15',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Gold',
    delegateType: 'null',
    holderAmount: '9865',
    delegateAmount: '0',
  },
  {
    User: 'she256.eth',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '2927',
  },
  {
    User: '0x46ab...b4d1',
    holderPoints: '0',
    delegatePoints: '1',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Bronze',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x3D2d...937C',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '3189',
  },
  {
    User: 'katiegarcia.eth',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'joxes.eth',
    holderPoints: '0',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'hi_Reverie',
    holderPoints: '0',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '404 DAO',
    holderPoints: '0',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x80FC...E482',
    holderPoints: '0',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x9950...3Cf4',
    holderPoints: '0',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '919',
  },
  {
    User: '0x8Ccd...f98d',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '4891',
  },
  {
    User: '0x11cf...d752',
    holderPoints: '0',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'PGov',
    holderPoints: '0',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'Tané',
    holderPoints: '15',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Gold',
    delegateType: 'null',
    holderAmount: '6204',
    delegateAmount: '0',
  },
  {
    User: '0x2B78...88f8',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '3947537',
    delegateAmount: '0',
  },
  {
    User: '0x2dEB...C399',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '6734227',
    delegateAmount: '0',
  },
  {
    User: '0x3951...A552',
    holderPoints: '5',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Silver',
    delegateType: 'null',
    holderAmount: '514',
    delegateAmount: '0',
  },
  {
    User: 'Wintermute Governanc…',
    holderPoints: '0',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'jacob.willemsma.eth',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0xB1EA...8251',
    holderPoints: '0',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'mihal.eth',
    holderPoints: '0',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '1751',
  },
  {
    User: 'Griff Green 🙏🌱🎗💜',
    holderPoints: '5',
    delegatePoints: '2',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Silver',
    delegateType: 'Silver',
    holderAmount: '567',
    delegateAmount: '2354',
  },
  {
    User: 'oilysirs.eth',
    holderPoints: '25',
    delegatePoints: '3',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'Gold',
    holderAmount: '73428',
    delegateAmount: '0',
  },
  {
    User: 'mjs.eth',
    holderPoints: '25',
    delegatePoints: '7',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '78513',
    delegateAmount: '0',
  },
  {
    User: 'theethernaut.eth',
    holderPoints: '50',
    delegatePoints: '7',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '8767083',
    delegateAmount: '0',
  },
  {
    User: 'Flipside Crypto',
    holderPoints: '50',
    delegatePoints: '5',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'Platnium',
    holderAmount: '9109237',
    delegateAmount: '4764',
  },
  {
    User: '0x8F54...1CC3',
    holderPoints: '0',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'Rick Dudley (afdudle…',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'yoav.eth',
    holderPoints: '5',
    delegatePoints: '1',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Silver',
    delegateType: 'Bronze',
    holderAmount: '999',
    delegateAmount: '0',
  },
  {
    User: '0xE1f8...0F53',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'CalBlockchain',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '8858025',
    delegateAmount: '0',
  },
  {
    User: '0xD0c4...B3D9',
    holderPoints: '25',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '88392',
    delegateAmount: '0',
  },
  {
    User: 'discusfish.eth',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '2427739',
    delegateAmount: '0',
  },
  {
    User: '0x9CBE...0a40',
    holderPoints: '25',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '34897',
    delegateAmount: '0',
  },
  {
    User: 'sugma.eth',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '3743089',
    delegateAmount: '0',
  },
  {
    User: 'Layer3',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '8766405',
    delegateAmount: '0',
  },
  {
    User: 'mattlosquadro.eth',
    holderPoints: '25',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '40270',
    delegateAmount: '0',
  },
  {
    User: '0xCc87...4c62',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '5263213',
    delegateAmount: '0',
  },
  {
    User: 'MinimalGravitas',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'pseudotheos.eth',
    holderPoints: '25',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '34958',
    delegateAmount: '0',
  },
  {
    User: '@ewokafloka',
    holderPoints: '50',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Platnium',
    holderAmount: '3467665',
    delegateAmount: '3237',
  },
  {
    User: '0x9b7D...E532',
    holderPoints: '50',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '1452606',
    delegateAmount: '0',
  },
  {
    User: '0x1383...Ae2A',
    holderPoints: '0',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x2C6c...2B63',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '3711',
  },
  {
    User: 'solarcurve.eth',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '3859',
  },
  {
    User: 'dhannte.eth',
    holderPoints: '0',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '1358',
  },
  {
    User: '0xc94a...c0Cd',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '2632',
  },
  {
    User: 'butterbum.eth',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '3335',
  },
  {
    User: '0xb074...8012',
    holderPoints: '15',
    delegatePoints: '2',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'Gold',
    delegateType: 'Silver',
    holderAmount: '4129',
    delegateAmount: '776',
  },
  {
    User: '@0xDonPepe',
    holderPoints: '3',
    delegatePoints: '7',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'null',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'forrestn.eth',
    holderPoints: '50',
    delegatePoints: '7',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '2042983',
    delegateAmount: '0',
  },
  {
    User: '0xdab0...5f5A',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: 'nathanvdh.eth',
    holderPoints: '100',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'WHALE',
    delegateType: 'Platnium',
    holderAmount: '951674104',
    delegateAmount: '2506',
  },
  {
    User: '0xeeF4...2018',
    holderPoints: '50',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '5992356',
    delegateAmount: '0',
  },
  {
    User: 'tongnk.eth',
    holderPoints: '100',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'WHALE',
    delegateType: 'Silver',
    holderAmount: '414118536',
    delegateAmount: '251',
  },
  {
    User: 'Exosphere',
    holderPoints: '50',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Gold',
    holderAmount: '7988569',
    delegateAmount: '0',
  },
  {
    User: 'ercwl',
    holderPoints: '50',
    delegatePoints: '1',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Bronze',
    holderAmount: '6272122',
    delegateAmount: '0',
  },
  {
    User: '0x0f97...4496',
    holderPoints: '50',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '5632667',
    delegateAmount: '0',
  },
  {
    User: 'mastermojo.eth',
    holderPoints: '15',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Gold',
    delegateType: 'Platnium',
    holderAmount: '4972',
    delegateAmount: '3232',
  },
  {
    User: 'advantageblockchain.…',
    holderPoints: '25',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'Gold',
    holderAmount: '86562',
    delegateAmount: '0',
  },
  {
    User: '0x0f94...9230',
    holderPoints: '25',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'Gold',
    holderAmount: '67613',
    delegateAmount: '0',
  },
  {
    User: 'esmeralda.eth',
    holderPoints: '50',
    delegatePoints: '7',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '7473340',
    delegateAmount: '0',
  },
  {
    User: 'itublockchain.eth',
    holderPoints: '50',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '9871969',
    delegateAmount: '0',
  },
  {
    User: 'hailvitalik.eth',
    holderPoints: '25',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '26798',
    delegateAmount: '0',
  },
  {
    User: 'voiceof.eth',
    holderPoints: '100',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'WHALE',
    delegateType: 'null',
    holderAmount: '164909786',
    delegateAmount: '0',
  },
  {
    User: 'web3magnetic',
    holderPoints: '15',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Gold',
    delegateType: 'Silver',
    holderAmount: '8057',
    delegateAmount: '1547',
  },
  {
    User: 'blockchainathopkins.…',
    holderPoints: '50',
    delegatePoints: '10',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '7965894',
    delegateAmount: '0',
  },
  {
    User: 'For StableLab, pleas…',
    holderPoints: '25',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'Silver',
    holderAmount: '20115',
    delegateAmount: '2056',
  },
  {
    User: 'scopelift.eth',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Platnium',
    holderAmount: '0',
    delegateAmount: '3486',
  },
  {
    User: '0xA3Eb...836a',
    holderPoints: '0',
    delegatePoints: '3',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Gold',
    holderAmount: '0',
    delegateAmount: '0',
  },
  {
    User: '0x03dD...92fA',
    holderPoints: '25',
    delegatePoints: '3',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'Gold',
    holderAmount: '20959',
    delegateAmount: '0',
  },
  {
    User: 'Ryan H.',
    holderPoints: '0',
    delegatePoints: '2',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '887',
  },
  {
    User: 'mikegriff.eth',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '2302824',
    delegateAmount: '0',
  },
  {
    User: '0xc420...073c',
    holderPoints: '25',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Platnium',
    delegateType: 'null',
    holderAmount: '87123',
    delegateAmount: '0',
  },
  {
    User: 'LaVeP',
    holderPoints: '15',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Gold',
    delegateType: 'null',
    holderAmount: '9890',
    delegateAmount: '0',
  },
  {
    User: '0x5a7F...0BA2',
    holderPoints: '50',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'null',
    holderAmount: '9138000',
    delegateAmount: '0',
  },
  {
    User: '0x73Ec...b07d',
    holderPoints: '5',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Silver',
    delegateType: 'null',
    holderAmount: '998',
    delegateAmount: '0',
  },
  /*  testing addresses     */
  {
    User: '0x316131DC685A63B1dbC8E0Fc6B893ec51CF159DA',
    holderPoints: '10',
    delegatePoints: '10',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Gold',
    holderAmount: '5700',
    delegateAmount: '800',
  },
  {
    User: '0x393053056EB678EA95CBc67CB7E1198184984707',
    holderPoints: '5',
    delegatePoints: '15',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Silver',
    delegateType: 'Silver',
    holderAmount: '200',
    delegateAmount: '74',
  },
  {
    User: '0xc0f2A154abA3f12D71AF25e87ca4f225B9C52203',
    holderPoints: '4',
    delegatePoints: '6',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'Silver',
    delegateType: 'Gold',
    holderAmount: '400',
    delegateAmount: '225',
  },
  {
    User: '0xcd192b61a8Dd586A97592555c1f5709e032F2505',
    holderPoints: '15',
    delegatePoints: '2',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Diamond',
    delegateType: 'Diamond',
    holderAmount: '54',
    delegateAmount: '25',
  },
  {
    User: '0xA1179f64638adb613DDAAc32D918EB6BEB824104',
    holderPoints: '2',
    delegatePoints: '0',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'Silver',
    delegateType: 'null',
    holderAmount: '45',
    delegateAmount: '0',
  },
  {
    User: '0x6eb78c56F639b3d161456e9f893c8e8aD9d754F0',
    holderPoints: '0',
    delegatePoints: '7',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '155',
  },
  {
    User: '0xD5db3F8B0a236176587460dC85F0fC5705D78477',
    holderPoints: '5',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'Gold',
    delegateType: 'Gold',
    holderAmount: '444',
    delegateAmount: '335',
  },
  {
    User: '0xe1e5dcbbc95aabe80e2f9c65c7a2cef85daf61c4',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '87',
  },
  {
    User: '0x33878e070db7f70D2953Fe0278Cd32aDf8104572',
    holderPoints: '20',
    delegatePoints: '5',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Gold',
    holderAmount: '4500',
    delegateAmount: '225',
  },
  {
    User: '0xB9573982875b83aaDc1296726E2ae77D13D9B98F',
    holderPoints: '0',
    delegatePoints: '5',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'null',
    delegateType: 'Silver',
    holderAmount: '0',
    delegateAmount: '200',
  },
  {
    User: '0x9FE099C5234E873551Fec5c7dd06E5213360A46c',
    holderPoints: '50',
    delegatePoints: '21',
    recipientsPoints: '0',
    badgeholderPoints: '0',
    holderType: 'Diamond',
    delegateType: 'Gold',
    holderAmount: '540',
    delegateAmount: '252',
  },
  {
    User: '0x44AC194359fA44eCe6Cb2E53E8c90547BCCb95a0',
    holderPoints: '100',
    delegatePoints: '8',
    recipientsPoints: '1',
    badgeholderPoints: '0',
    holderType: 'WHALE',
    delegateType: 'Silver',
    holderAmount: '4800',
    delegateAmount: '250',
  },
  {
    User: '0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8',
    holderPoints: '5',
    delegatePoints: '15',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'Bronze',
    delegateType: 'Platnium',
    holderAmount: '200',
    delegateAmount: '1450',
  },
  {
    User: '0x871Cd6353B803CECeB090Bb827Ecb2F361Db81AB',
    holderPoints: '8',
    delegatePoints: '1',
    recipientsPoints: '0',
    badgeholderPoints: '1',
    holderType: 'Bronze',
    delegateType: 'Bronze',
    holderAmount: '21',
    delegateAmount: '15',
  },
  {
    User: '0x501EcB2eD1BAFeEDCB122B321618044C07e6C324',
    holderPoints: '25',
    delegatePoints: '15',
    recipientsPoints: '1',
    badgeholderPoints: '1',
    holderType: 'Platnium',
    delegateType: 'Gold',
    holderAmount: '5000',
    delegateAmount: '4000',
  },
] as const;
