name: rf4-deploy-pipeline

on:
  push:
    branches:
      - rf4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Redeploy rf4
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd rpgf4-pw-backend
            docker-compose down -v
            docker image prune -a --force
            git checkout rf4
            git reset --hard origin/rf4
            git pull origin rf4
            docker-compose build --no-cache
            docker-compose up -d