name: rpgf5-prod-deploy-pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/generalmagicio/rpgf5-be:main

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: SSH and Redeploy Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RPGF5_PROD_HOST }}
          username: ${{ secrets.RPGF5_PROD_USERNAME }}
          key: ${{ secrets.RPGF5_PROD_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd pw-backend
            git reset --hard HEAD~1
            git checkout master
            git pull origin master
            docker image prune -a --force
            docker compose -f docker-compose-prod.yml pull

            ## Update each backend service one by one
            docker compose -f docker-compose-prod.yml up -d --no-deps --scale pw-backend1=0 --scale pw-backend2=1
            docker compose -f docker-compose-prod.yml up -d
            # Check the health of pw-backend1
            if [ "$(docker inspect --format='{{json .State.Status}}' pw-backend1)" != "\"running\"" ]; then
              echo "pw-backend1 is not running, stopping deployment"
              exit 1
            fi

            docker compose -f docker-compose-prod.yml up -d --no-deps --scale pw-backend1=1 --scale pw-backend2=0
            docker compose -f docker-compose-prod.yml up -d
            # Check the health of pw-backend2
            if [ "$(docker inspect --format='{{json .State.Status}}' pw-backend2)" != "\"running\"" ]; then
              echo "pw-backend2 is not running, stopping deployment"
              exit 1
            fi